---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2018-12-17 at 11-54-00 AM/Screen Shot 2018-12-17 at
      11-54-00 AM.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/82133/articles/340617/master/file/figures/Screen%20Shot%202018-12-17%20at%2011-54-00%20AM/Screen%20Shot%202018-12-17%20at%2011-54-00%20AM.png"
