---
version: 2
multicolumn: false
web-width: 700px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screen Shot 2018-12-18 at 4-46-15 PM/Screen Shot 2018-12-18 at 4-46-15
      PM.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/82133/articles/340617/master/file/figures/Screen%20Shot%202018-12-18%20at%204-46-15%20PM/Screen%20Shot%202018-12-18%20at%204-46-15%20PM.png"
    folder_url: "/users/82133/articles/340617/master/folder/figures/Screen Shot 2018-12-18
      at 4-46-15 PM"
